### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by Chinaxxf** [ju-lab/LungCancer_SV_timing_analyses#1]
"r01_human_g1k_v37.fasta.100kb", this file is used in 10-1. Calculate absCN of each 100Kb bin
![image](https://user-images.githubusercontent.com/48044969/59437762-bfd6c100-8e24-11e9-965f-2b927f0276ae.png),but i can not find it

**Comment by seongyeol-park** [comment]
Thank you. I added the file and edit the script.
